name: Poseidon Bot
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Binderbot Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install Binderbot from github master
        run: pip install git+https://github.com/pangeo-gallery/binderbot.git
      - name: Build notebooks using Binderbot
        run: >
          python -m binderbot.cli --binder-url https://binder.pangeo.io/
          --repo rabernat/poseidon-bot --ref binder
          --pass-env-var TWITTER_SECRET
          llcbot.ipynb
